### ISSUE TITLE
Latex Memory Size Issues

### ISSUE THREAD

**Issue by Ahoybrause** [pedro-callil/tikzviolinplots#1]
Very nice that you realized violin plots for tikz. Thank you!
Unfortunately, violin plots often result out of many data points.
Do you have a solution for memory size issues with latex in mind?

**Comment by pedro-callil** [comment]
Hello @Ahoybrause,

Thanks for the kind words.

Are you using `pdflatex` to compile your documents? If yes, the problem might be solved by switching to the `lualatex` executable (which also comes with most TeX distributions and should work as a drop-in replacement, requiring no modifications of the source files).

If such change is impossible, you could increase the amount of memory available to TeX. This is a distribution-specific configuration, and without further details nothing else can be said. However, instructions for TeXLive (and similar distributions) and MiKTeX are available in sections 6.1 and mainly 6.2 of the [manual](http://mirrors.ctan.org/graphics/pgf/contrib/pgfplots/doc/pgfplots.pdf) of the package `pgfplots`.

Specifically about `tikzviolinplots`, you can change the number of samples (with the `samples` option, for both `\violinplot` and `\violinplotwholefile`). Reducing it increases the number of points that can be plotted without problems; however, the smoothness of the curves is visibly impacted for very low values.

Finally, it might be useful to check if the number of data points can't be, somehow, reduced; plotting your curves with only a small random sample of your data points might be, visually, indistinguishable from plotting your whole data set.

Best regards,
Pedro Callil.
